### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UntitledProject1)
add_subdirectory(UntitledProject1Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProject1plugin
    UntitledProject1Contentplugin
    QtQuickDesignerComponents)